INSERT INTO genre (genre_name) VALUES ('Pop');
INSERT INTO genre (genre_name) VALUES ('Hip-Hop');
INSERT INTO genre (genre_name) VALUES ('Rap');
INSERT INTO genre (genre_name) VALUES ('Trap');
INSERT INTO genre (genre_name) VALUES ('Rock');
INSERT INTO genre (genre_name) VALUES ('Alternative Rock');
INSERT INTO genre (genre_name) VALUES ('Indie Rock');
INSERT INTO genre (genre_name) VALUES ('Punk');
INSERT INTO genre (genre_name) VALUES ('Pop-Punk');
INSERT INTO genre (genre_name) VALUES ('Heavy Metal');
INSERT INTO genre (genre_name) VALUES ('R&B (Rhythm and Blues)');
INSERT INTO genre (genre_name) VALUES ('Soul');
INSERT INTO genre (genre_name) VALUES ('Neo-Soul');
INSERT INTO genre (genre_name) VALUES ('Funk');
INSERT INTO genre (genre_name) VALUES ('Contemporary Country');
INSERT INTO genre (genre_name) VALUES ('Americana');
INSERT INTO genre (genre_name) VALUES ('Bluegrass');
INSERT INTO genre (genre_name) VALUES ('Folk');
INSERT INTO genre (genre_name) VALUES ('Indie Folk');
INSERT INTO genre (genre_name) VALUES ('House');
INSERT INTO genre (genre_name) VALUES ('Techno');
INSERT INTO genre (genre_name) VALUES ('Dubstep');
INSERT INTO genre (genre_name) VALUES ('Drum and Bass');
INSERT INTO genre (genre_name) VALUES ('Synth-Pop');
INSERT INTO genre (genre_name) VALUES ('Electropop');
INSERT INTO genre (genre_name) VALUES ('Hyperpop');
INSERT INTO genre (genre_name) VALUES ('Reggaeton');
INSERT INTO genre (genre_name) VALUES ('Salsa');
INSERT INTO genre (genre_name) VALUES ('Bachata');
INSERT INTO genre (genre_name) VALUES ('Regional Mexican');
INSERT INTO genre (genre_name) VALUES ('Afrobeats');
INSERT INTO genre (genre_name) VALUES ('Amapiano');
INSERT INTO genre (genre_name) VALUES ('K-Pop');
INSERT INTO genre (genre_name) VALUES ('J-Pop');
INSERT INTO genre (genre_name) VALUES ('Jazz');
INSERT INTO genre (genre_name) VALUES ('Smooth Jazz');
INSERT INTO genre (genre_name) VALUES ('Blues');
INSERT INTO genre (genre_name) VALUES ('Blues Rock');
INSERT INTO genre (genre_name) VALUES ('Reggae');
INSERT INTO genre (genre_name) VALUES ('Ska');
INSERT INTO genre (genre_name) VALUES ('Disco');
INSERT INTO genre (genre_name) VALUES ('Classical');
INSERT INTO genre (genre_name) VALUES ('Cinematic');
INSERT INTO genre (genre_name) VALUES ('Ambient');
INSERT INTO genre (genre_name) VALUES ('Lo-fi Hip-Hop');
INSERT INTO genre (genre_name) VALUES ('Phonk');
INSERT INTO genre (genre_name) VALUES ('Drill');
INSERT INTO genre (genre_name) VALUES ('Emo Rap');
INSERT INTO genre (genre_name) VALUES ('Grunge');
INSERT INTO genre (genre_name) VALUES ('Shoegaze');