-- Clearing tables
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT tablename
        FROM pg_tables
        WHERE schemaname = 'public'
    LOOP
        EXECUTE
            'TRUNCATE TABLE public.' || quote_ident(r.tablename) || ' RESTART IDENTITY CASCADE';
    END LOOP;
END $$;

-- Country table
INSERT INTO country (country_name) VALUES ('Afghanistan');
INSERT INTO country (country_name) VALUES ('Albania');
INSERT INTO country (country_name) VALUES ('Algeria');
INSERT INTO country (country_name) VALUES ('Andorra');
INSERT INTO country (country_name) VALUES ('Angola');
INSERT INTO country (country_name) VALUES ('Antigua and Barbuda');
INSERT INTO country (country_name) VALUES ('Argentina');
INSERT INTO country (country_name) VALUES ('Armenia');
INSERT INTO country (country_name) VALUES ('Australia');
INSERT INTO country (country_name) VALUES ('Austria');
INSERT INTO country (country_name) VALUES ('Azerbaijan');
INSERT INTO country (country_name) VALUES ('Bahamas');
INSERT INTO country (country_name) VALUES ('Bahrain');
INSERT INTO country (country_name) VALUES ('Bangladesh');
INSERT INTO country (country_name) VALUES ('Barbados');
INSERT INTO country (country_name) VALUES ('Belarus');
INSERT INTO country (country_name) VALUES ('Belgium');
INSERT INTO country (country_name) VALUES ('Belize');
INSERT INTO country (country_name) VALUES ('Benin');
INSERT INTO country (country_name) VALUES ('Bhutan');
INSERT INTO country (country_name) VALUES ('Bolivia');
INSERT INTO country (country_name) VALUES ('Bosnia and Herzegovina');
INSERT INTO country (country_name) VALUES ('Botswana');
INSERT INTO country (country_name) VALUES ('Brazil');
INSERT INTO country (country_name) VALUES ('Brunei');
INSERT INTO country (country_name) VALUES ('Bulgaria');
INSERT INTO country (country_name) VALUES ('Burkina Faso');
INSERT INTO country (country_name) VALUES ('Burundi');
INSERT INTO country (country_name) VALUES ('Cabo Verde');
INSERT INTO country (country_name) VALUES ('Cambodia');
INSERT INTO country (country_name) VALUES ('Cameroon');
INSERT INTO country (country_name) VALUES ('Canada');
INSERT INTO country (country_name) VALUES ('Central African Republic');
INSERT INTO country (country_name) VALUES ('Chad');
INSERT INTO country (country_name) VALUES ('Chile');
INSERT INTO country (country_name) VALUES ('China');
INSERT INTO country (country_name) VALUES ('Colombia');
INSERT INTO country (country_name) VALUES ('Comoros');
INSERT INTO country (country_name) VALUES ('Congo (Congo-Brazzaville)');
INSERT INTO country (country_name) VALUES ('Costa Rica');
INSERT INTO country (country_name) VALUES ('Croatia');
INSERT INTO country (country_name) VALUES ('Cuba');
INSERT INTO country (country_name) VALUES ('Cyprus');
INSERT INTO country (country_name) VALUES ('Czechia');
INSERT INTO country (country_name) VALUES ('Denmark');
INSERT INTO country (country_name) VALUES ('Djibouti');
INSERT INTO country (country_name) VALUES ('Dominica');
INSERT INTO country (country_name) VALUES ('Dominican Republic');
INSERT INTO country (country_name) VALUES ('Ecuador');
INSERT INTO country (country_name) VALUES ('Egypt');
INSERT INTO country (country_name) VALUES ('El Salvador');
INSERT INTO country (country_name) VALUES ('Equatorial Guinea');
INSERT INTO country (country_name) VALUES ('Eritrea');
INSERT INTO country (country_name) VALUES ('Estonia');
INSERT INTO country (country_name) VALUES ('Eswatini');
INSERT INTO country (country_name) VALUES ('Ethiopia');
INSERT INTO country (country_name) VALUES ('Fiji');
INSERT INTO country (country_name) VALUES ('Finland');
INSERT INTO country (country_name) VALUES ('France');
INSERT INTO country (country_name) VALUES ('Gabon');
INSERT INTO country (country_name) VALUES ('Gambia');
INSERT INTO country (country_name) VALUES ('Georgia');
INSERT INTO country (country_name) VALUES ('Germany');
INSERT INTO country (country_name) VALUES ('Ghana');
INSERT INTO country (country_name) VALUES ('Greece');
INSERT INTO country (country_name) VALUES ('Grenada');
INSERT INTO country (country_name) VALUES ('Guatemala');
INSERT INTO country (country_name) VALUES ('Guinea');
INSERT INTO country (country_name) VALUES ('Guinea-Bissau');
INSERT INTO country (country_name) VALUES ('Guyana');
INSERT INTO country (country_name) VALUES ('Haiti');
INSERT INTO country (country_name) VALUES ('Honduras');
INSERT INTO country (country_name) VALUES ('Hungary');
INSERT INTO country (country_name) VALUES ('Iceland');
INSERT INTO country (country_name) VALUES ('India');
INSERT INTO country (country_name) VALUES ('Indonesia');
INSERT INTO country (country_name) VALUES ('Iran');
INSERT INTO country (country_name) VALUES ('Iraq');
INSERT INTO country (country_name) VALUES ('Ireland');
INSERT INTO country (country_name) VALUES ('Israel');
INSERT INTO country (country_name) VALUES ('Italy');
INSERT INTO country (country_name) VALUES ('Jamaica');
INSERT INTO country (country_name) VALUES ('Japan');
INSERT INTO country (country_name) VALUES ('Jordan');
INSERT INTO country (country_name) VALUES ('Kazakhstan');
INSERT INTO country (country_name) VALUES ('Kenya');
INSERT INTO country (country_name) VALUES ('Kiribati');
INSERT INTO country (country_name) VALUES ('Kuwait');
INSERT INTO country (country_name) VALUES ('Kyrgyzstan');
INSERT INTO country (country_name) VALUES ('Laos');
INSERT INTO country (country_name) VALUES ('Latvia');
INSERT INTO country (country_name) VALUES ('Lebanon');
INSERT INTO country (country_name) VALUES ('Lesotho');
INSERT INTO country (country_name) VALUES ('Liberia');
INSERT INTO country (country_name) VALUES ('Libya');
INSERT INTO country (country_name) VALUES ('Liechtenstein');
INSERT INTO country (country_name) VALUES ('Lithuania');
INSERT INTO country (country_name) VALUES ('Luxembourg');
INSERT INTO country (country_name) VALUES ('Madagascar');
INSERT INTO country (country_name) VALUES ('Malawi');
INSERT INTO country (country_name) VALUES ('Malaysia');
INSERT INTO country (country_name) VALUES ('Maldives');
INSERT INTO country (country_name) VALUES ('Mali');
INSERT INTO country (country_name) VALUES ('Malta');
INSERT INTO country (country_name) VALUES ('Marshall Islands');
INSERT INTO country (country_name) VALUES ('Mauritania');
INSERT INTO country (country_name) VALUES ('Mauritius');
INSERT INTO country (country_name) VALUES ('Mexico');
INSERT INTO country (country_name) VALUES ('Micronesia');
INSERT INTO country (country_name) VALUES ('Moldova');
INSERT INTO country (country_name) VALUES ('Monaco');
INSERT INTO country (country_name) VALUES ('Mongolia');
INSERT INTO country (country_name) VALUES ('Montenegro');
INSERT INTO country (country_name) VALUES ('Morocco');
INSERT INTO country (country_name) VALUES ('Mozambique');
INSERT INTO country (country_name) VALUES ('Myanmar');
INSERT INTO country (country_name) VALUES ('Namibia');
INSERT INTO country (country_name) VALUES ('Nauru');
INSERT INTO country (country_name) VALUES ('Nepal');
INSERT INTO country (country_name) VALUES ('Netherlands');
INSERT INTO country (country_name) VALUES ('New Zealand');
INSERT INTO country (country_name) VALUES ('Nicaragua');
INSERT INTO country (country_name) VALUES ('Niger');
INSERT INTO country (country_name) VALUES ('Nigeria');
INSERT INTO country (country_name) VALUES ('North Korea');
INSERT INTO country (country_name) VALUES ('North Macedonia');
INSERT INTO country (country_name) VALUES ('Norway');
INSERT INTO country (country_name) VALUES ('Oman');
INSERT INTO country (country_name) VALUES ('Pakistan');
INSERT INTO country (country_name) VALUES ('Palau');
INSERT INTO country (country_name) VALUES ('Palestine');
INSERT INTO country (country_name) VALUES ('Panama');
INSERT INTO country (country_name) VALUES ('Papua New Guinea');
INSERT INTO country (country_name) VALUES ('Paraguay');
INSERT INTO country (country_name) VALUES ('Peru');
INSERT INTO country (country_name) VALUES ('Philippines');
INSERT INTO country (country_name) VALUES ('Poland');
INSERT INTO country (country_name) VALUES ('Portugal');
INSERT INTO country (country_name) VALUES ('Qatar');
INSERT INTO country (country_name) VALUES ('Romania');
INSERT INTO country (country_name) VALUES ('Russia');
INSERT INTO country (country_name) VALUES ('Rwanda');
INSERT INTO country (country_name) VALUES ('Saint Kitts and Nevis');
INSERT INTO country (country_name) VALUES ('Saint Lucia');
INSERT INTO country (country_name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO country (country_name) VALUES ('Samoa');
INSERT INTO country (country_name) VALUES ('San Marino');
INSERT INTO country (country_name) VALUES ('Sao Tome and Principe');
INSERT INTO country (country_name) VALUES ('Saudi Arabia');
INSERT INTO country (country_name) VALUES ('Senegal');
INSERT INTO country (country_name) VALUES ('Serbia');
INSERT INTO country (country_name) VALUES ('Seychelles');
INSERT INTO country (country_name) VALUES ('Sierra Leone');
INSERT INTO country (country_name) VALUES ('Singapore');
INSERT INTO country (country_name) VALUES ('Slovakia');
INSERT INTO country (country_name) VALUES ('Slovenia');
INSERT INTO country (country_name) VALUES ('Solomon Islands');
INSERT INTO country (country_name) VALUES ('Somalia');
INSERT INTO country (country_name) VALUES ('South Africa');
INSERT INTO country (country_name) VALUES ('South Korea');
INSERT INTO country (country_name) VALUES ('South Sudan');
INSERT INTO country (country_name) VALUES ('Spain');
INSERT INTO country (country_name) VALUES ('Sri Lanka');
INSERT INTO country (country_name) VALUES ('Sudan');
INSERT INTO country (country_name) VALUES ('Suriname');
INSERT INTO country (country_name) VALUES ('Sweden');
INSERT INTO country (country_name) VALUES ('Switzerland');
INSERT INTO country (country_name) VALUES ('Syria');
INSERT INTO country (country_name) VALUES ('Taiwan');
INSERT INTO country (country_name) VALUES ('Tajikistan');
INSERT INTO country (country_name) VALUES ('Tanzania');
INSERT INTO country (country_name) VALUES ('Thailand');
INSERT INTO country (country_name) VALUES ('Timor-Leste');
INSERT INTO country (country_name) VALUES ('Togo');
INSERT INTO country (country_name) VALUES ('Tonga');
INSERT INTO country (country_name) VALUES ('Trinidad and Tobago');
INSERT INTO country (country_name) VALUES ('Tunisia');
INSERT INTO country (country_name) VALUES ('Turkey');
INSERT INTO country (country_name) VALUES ('Turkmenistan');
INSERT INTO country (country_name) VALUES ('Tuvalu');
INSERT INTO country (country_name) VALUES ('Uganda');
INSERT INTO country (country_name) VALUES ('Ukraine');
INSERT INTO country (country_name) VALUES ('United Arab Emirates');
INSERT INTO country (country_name) VALUES ('United Kingdom');
INSERT INTO country (country_name) VALUES ('United States');
INSERT INTO country (country_name) VALUES ('Uruguay');
INSERT INTO country (country_name) VALUES ('Uzbekistan');
INSERT INTO country (country_name) VALUES ('Vanuatu');
INSERT INTO country (country_name) VALUES ('Vatican City');
INSERT INTO country (country_name) VALUES ('Venezuela');
INSERT INTO country (country_name) VALUES ('Vietnam');
INSERT INTO country (country_name) VALUES ('Yemen');
INSERT INTO country (country_name) VALUES ('Zambia');
INSERT INTO country (country_name) VALUES ('Zimbabwe');

-- Language table
INSERT INTO language (language_name) VALUES ('Afrikaans');
INSERT INTO language (language_name) VALUES ('Albanian');
INSERT INTO language (language_name) VALUES ('Amharic');
INSERT INTO language (language_name) VALUES ('Arabic');
INSERT INTO language (language_name) VALUES ('Armenian');
INSERT INTO language (language_name) VALUES ('Assamese');
INSERT INTO language (language_name) VALUES ('Azerbaijani');
INSERT INTO language (language_name) VALUES ('Basque');
INSERT INTO language (language_name) VALUES ('Belarusian');
INSERT INTO language (language_name) VALUES ('Bengali');
INSERT INTO language (language_name) VALUES ('Bhojpuri');
INSERT INTO language (language_name) VALUES ('Bosnian');
INSERT INTO language (language_name) VALUES ('Bulgarian');
INSERT INTO language (language_name) VALUES ('Burmese');
INSERT INTO language (language_name) VALUES ('Catalan');
INSERT INTO language (language_name) VALUES ('Cebuano');
INSERT INTO language (language_name) VALUES ('Chichewa');
INSERT INTO language (language_name) VALUES ('Chinese (Mandarin)');
INSERT INTO language (language_name) VALUES ('Chinese (Cantonese)');
INSERT INTO language (language_name) VALUES ('Corsican');
INSERT INTO language (language_name) VALUES ('Croatian');
INSERT INTO language (language_name) VALUES ('Czech');
INSERT INTO language (language_name) VALUES ('Danish');
INSERT INTO language (language_name) VALUES ('Dari');
INSERT INTO language (language_name) VALUES ('Divehi');
INSERT INTO language (language_name) VALUES ('Dutch');
INSERT INTO language (language_name) VALUES ('English');
INSERT INTO language (language_name) VALUES ('Esperanto');
INSERT INTO language (language_name) VALUES ('Estonian');
INSERT INTO language (language_name) VALUES ('Ewe');
INSERT INTO language (language_name) VALUES ('Faroese');
INSERT INTO language (language_name) VALUES ('Fijian');
INSERT INTO language (language_name) VALUES ('Finnish');
INSERT INTO language (language_name) VALUES ('French');
INSERT INTO language (language_name) VALUES ('Frisian');
INSERT INTO language (language_name) VALUES ('Galician');
INSERT INTO language (language_name) VALUES ('Georgian');
INSERT INTO language (language_name) VALUES ('German');
INSERT INTO language (language_name) VALUES ('Greek');
INSERT INTO language (language_name) VALUES ('Gujarati');
INSERT INTO language (language_name) VALUES ('Haitian Creole');
INSERT INTO language (language_name) VALUES ('Hausa');
INSERT INTO language (language_name) VALUES ('Hawaiian');
INSERT INTO language (language_name) VALUES ('Hebrew');
INSERT INTO language (language_name) VALUES ('Hindi');
INSERT INTO language (language_name) VALUES ('Hmong');
INSERT INTO language (language_name) VALUES ('Hungarian');
INSERT INTO language (language_name) VALUES ('Icelandic');
INSERT INTO language (language_name) VALUES ('Igbo');
INSERT INTO language (language_name) VALUES ('Ilocano');
INSERT INTO language (language_name) VALUES ('Indonesian');
INSERT INTO language (language_name) VALUES ('Irish');
INSERT INTO language (language_name) VALUES ('Italian');
INSERT INTO language (language_name) VALUES ('Japanese');
INSERT INTO language (language_name) VALUES ('Javanese');
INSERT INTO language (language_name) VALUES ('Kannada');
INSERT INTO language (language_name) VALUES ('Kazakh');
INSERT INTO language (language_name) VALUES ('Khmer');
INSERT INTO language (language_name) VALUES ('Kinyarwanda');
INSERT INTO language (language_name) VALUES ('Korean');
INSERT INTO language (language_name) VALUES ('Kurdish');
INSERT INTO language (language_name) VALUES ('Kyrgyz');
INSERT INTO language (language_name) VALUES ('Lao');
INSERT INTO language (language_name) VALUES ('Latin');
INSERT INTO language (language_name) VALUES ('Latvian');
INSERT INTO language (language_name) VALUES ('Lithuanian');
INSERT INTO language (language_name) VALUES ('Luxembourgish');
INSERT INTO language (language_name) VALUES ('Macedonian');
INSERT INTO language (language_name) VALUES ('Malagasy');
INSERT INTO language (language_name) VALUES ('Malay');
INSERT INTO language (language_name) VALUES ('Malayalam');
INSERT INTO language (language_name) VALUES ('Maltese');
INSERT INTO language (language_name) VALUES ('Maori');
INSERT INTO language (language_name) VALUES ('Marathi');
INSERT INTO language (language_name) VALUES ('Mongolian');
INSERT INTO language (language_name) VALUES ('Nepali');
INSERT INTO language (language_name) VALUES ('Norwegian');
INSERT INTO language (language_name) VALUES ('Odia');
INSERT INTO language (language_name) VALUES ('Oromo');
INSERT INTO language (language_name) VALUES ('Pashto');
INSERT INTO language (language_name) VALUES ('Persian');
INSERT INTO language (language_name) VALUES ('Polish');
INSERT INTO language (language_name) VALUES ('Portuguese');
INSERT INTO language (language_name) VALUES ('Punjabi');
INSERT INTO language (language_name) VALUES ('Quechua');
INSERT INTO language (language_name) VALUES ('Romanian');
INSERT INTO language (language_name) VALUES ('Russian');
INSERT INTO language (language_name) VALUES ('Samoan');
INSERT INTO language (language_name) VALUES ('Scottish Gaelic');
INSERT INTO language (language_name) VALUES ('Serbian');
INSERT INTO language (language_name) VALUES ('Sesotho');
INSERT INTO language (language_name) VALUES ('Shona');
INSERT INTO language (language_name) VALUES ('Sindhi');
INSERT INTO language (language_name) VALUES ('Sinhala');
INSERT INTO language (language_name) VALUES ('Slovak');
INSERT INTO language (language_name) VALUES ('Slovenian');
INSERT INTO language (language_name) VALUES ('Somali');
INSERT INTO language (language_name) VALUES ('Spanish');
INSERT INTO language (language_name) VALUES ('Sundanese');
INSERT INTO language (language_name) VALUES ('Swahili');
INSERT INTO language (language_name) VALUES ('Swedish');
INSERT INTO language (language_name) VALUES ('Tagalog');
INSERT INTO language (language_name) VALUES ('Tajik');
INSERT INTO language (language_name) VALUES ('Tamil');
INSERT INTO language (language_name) VALUES ('Tatar');
INSERT INTO language (language_name) VALUES ('Telugu');
INSERT INTO language (language_name) VALUES ('Thai');
INSERT INTO language (language_name) VALUES ('Tigrinya');
INSERT INTO language (language_name) VALUES ('Turkish');
INSERT INTO language (language_name) VALUES ('Turkmen');
INSERT INTO language (language_name) VALUES ('Ukrainian');
INSERT INTO language (language_name) VALUES ('Urdu');
INSERT INTO language (language_name) VALUES ('Uyghur');
INSERT INTO language (language_name) VALUES ('Uzbek');
INSERT INTO language (language_name) VALUES ('Vietnamese');
INSERT INTO language (language_name) VALUES ('Welsh');
INSERT INTO language (language_name) VALUES ('Xhosa');
INSERT INTO language (language_name) VALUES ('Yiddish');
INSERT INTO language (language_name) VALUES ('Yoruba');
INSERT INTO language (language_name) VALUES ('Zulu');

-- Genre table
INSERT INTO genre (genre_name) VALUES ('Pop');
INSERT INTO genre (genre_name) VALUES ('Hip-Hop');
INSERT INTO genre (genre_name) VALUES ('Rap');
INSERT INTO genre (genre_name) VALUES ('Trap');
INSERT INTO genre (genre_name) VALUES ('Rock');
INSERT INTO genre (genre_name) VALUES ('Alternative Rock');
INSERT INTO genre (genre_name) VALUES ('Indie Rock');
INSERT INTO genre (genre_name) VALUES ('Punk');
INSERT INTO genre (genre_name) VALUES ('Pop-Punk');
INSERT INTO genre (genre_name) VALUES ('Heavy Metal');
INSERT INTO genre (genre_name) VALUES ('R&B (Rhythm and Blues)');
INSERT INTO genre (genre_name) VALUES ('Soul');
INSERT INTO genre (genre_name) VALUES ('Neo-Soul');
INSERT INTO genre (genre_name) VALUES ('Funk');
INSERT INTO genre (genre_name) VALUES ('Contemporary Country');
INSERT INTO genre (genre_name) VALUES ('Americana');
INSERT INTO genre (genre_name) VALUES ('Bluegrass');
INSERT INTO genre (genre_name) VALUES ('Folk');
INSERT INTO genre (genre_name) VALUES ('Indie Folk');
INSERT INTO genre (genre_name) VALUES ('House');
INSERT INTO genre (genre_name) VALUES ('Techno');
INSERT INTO genre (genre_name) VALUES ('Dubstep');
INSERT INTO genre (genre_name) VALUES ('Drum and Bass');
INSERT INTO genre (genre_name) VALUES ('Synth-Pop');
INSERT INTO genre (genre_name) VALUES ('Electropop');
INSERT INTO genre (genre_name) VALUES ('Hyperpop');
INSERT INTO genre (genre_name) VALUES ('Reggaeton');
INSERT INTO genre (genre_name) VALUES ('Salsa');
INSERT INTO genre (genre_name) VALUES ('Bachata');
INSERT INTO genre (genre_name) VALUES ('Regional Mexican');
INSERT INTO genre (genre_name) VALUES ('Afrobeats');
INSERT INTO genre (genre_name) VALUES ('Amapiano');
INSERT INTO genre (genre_name) VALUES ('K-Pop');
INSERT INTO genre (genre_name) VALUES ('J-Pop');
INSERT INTO genre (genre_name) VALUES ('Jazz');
INSERT INTO genre (genre_name) VALUES ('Smooth Jazz');
INSERT INTO genre (genre_name) VALUES ('Blues');
INSERT INTO genre (genre_name) VALUES ('Blues Rock');
INSERT INTO genre (genre_name) VALUES ('Reggae');
INSERT INTO genre (genre_name) VALUES ('Ska');
INSERT INTO genre (genre_name) VALUES ('Disco');
INSERT INTO genre (genre_name) VALUES ('Classical');
INSERT INTO genre (genre_name) VALUES ('Cinematic');
INSERT INTO genre (genre_name) VALUES ('Ambient');
INSERT INTO genre (genre_name) VALUES ('Lo-fi Hip-Hop');
INSERT INTO genre (genre_name) VALUES ('Phonk');
INSERT INTO genre (genre_name) VALUES ('Drill');
INSERT INTO genre (genre_name) VALUES ('Emo Rap');
INSERT INTO genre (genre_name) VALUES ('Grunge');
INSERT INTO genre (genre_name) VALUES ('Shoegaze');

-- Mood table
INSERT INTO mood (mood_name) VALUES ('Happy');
INSERT INTO mood (mood_name) VALUES ('Sad');
INSERT INTO mood (mood_name) VALUES ('Chill');
INSERT INTO mood (mood_name) VALUES ('Hype');
INSERT INTO mood (mood_name) VALUES ('Calm');
INSERT INTO mood (mood_name) VALUES ('Romantic');
INSERT INTO mood (mood_name) VALUES ('Angry');
INSERT INTO mood (mood_name) VALUES ('Melancholic');
INSERT INTO mood (mood_name) VALUES ('Confident');
INSERT INTO mood (mood_name) VALUES ('Dreamy');
INSERT INTO mood (mood_name) VALUES ('Nostalgic');
INSERT INTO mood (mood_name) VALUES ('Focused');
INSERT INTO mood (mood_name) VALUES ('Euphoric');
INSERT INTO mood (mood_name) VALUES ('Anxious');
INSERT INTO mood (mood_name) VALUES ('Lonely');
INSERT INTO mood (mood_name) VALUES ('Inspirational');
INSERT INTO mood (mood_name) VALUES ('Mysterious');
INSERT INTO mood (mood_name) VALUES ('Sensual');
INSERT INTO mood (mood_name) VALUES ('Playful');
INSERT INTO mood (mood_name) VALUES ('Rebellious');
INSERT INTO mood (mood_name) VALUES ('Trippy');
INSERT INTO mood (mood_name) VALUES ('Epic');
INSERT INTO mood (mood_name) VALUES ('Bittersweet');
INSERT INTO mood (mood_name) VALUES ('Dark');
INSERT INTO mood (mood_name) VALUES ('Hopeful');
INSERT INTO mood (mood_name) VALUES ('Rowdy');
INSERT INTO mood (mood_name) VALUES ('Spooky');
INSERT INTO mood (mood_name) VALUES ('Savage');
INSERT INTO mood (mood_name) VALUES ('Peaceful');
INSERT INTO mood (mood_name) VALUES ('Whimsical');

-- Instrument table
INSERT INTO instrument (instrument_name) VALUES ('Lead Vocals');
INSERT INTO instrument (instrument_name) VALUES ('Backing Vocals');
INSERT INTO instrument (instrument_name) VALUES ('Guitar');
INSERT INTO instrument (instrument_name) VALUES ('Acoustic Guitar');
INSERT INTO instrument (instrument_name) VALUES ('Electric Guitar');
INSERT INTO instrument (instrument_name) VALUES ('Bass Guitar');
INSERT INTO instrument (instrument_name) VALUES ('Ukulele');
INSERT INTO instrument (instrument_name) VALUES ('Banjo');
INSERT INTO instrument (instrument_name) VALUES ('Mandolin');
INSERT INTO instrument (instrument_name) VALUES ('Harp');
INSERT INTO instrument (instrument_name) VALUES ('Piano');
INSERT INTO instrument (instrument_name) VALUES ('Keyboard');
INSERT INTO instrument (instrument_name) VALUES ('Synthesizer');
INSERT INTO instrument (instrument_name) VALUES ('Organ');
INSERT INTO instrument (instrument_name) VALUES ('Drums');
INSERT INTO instrument (instrument_name) VALUES ('Drum Kit');
INSERT INTO instrument (instrument_name) VALUES ('Snare Drum');
INSERT INTO instrument (instrument_name) VALUES ('Bass Drum');
INSERT INTO instrument (instrument_name) VALUES ('Cymbals');
INSERT INTO instrument (instrument_name) VALUES ('Xylophone');
INSERT INTO instrument (instrument_name) VALUES ('Violin');
INSERT INTO instrument (instrument_name) VALUES ('Viola');
INSERT INTO instrument (instrument_name) VALUES ('Cello');
INSERT INTO instrument (instrument_name) VALUES ('Double Bass');
INSERT INTO instrument (instrument_name) VALUES ('Flute');
INSERT INTO instrument (instrument_name) VALUES ('Clarinet');
INSERT INTO instrument (instrument_name) VALUES ('Saxophone');
INSERT INTO instrument (instrument_name) VALUES ('Bassoon');
INSERT INTO instrument (instrument_name) VALUES ('Trumpet');
INSERT INTO instrument (instrument_name) VALUES ('Trombone');
INSERT INTO instrument (instrument_name) VALUES ('French Horn');
INSERT INTO instrument (instrument_name) VALUES ('Tuba');
INSERT INTO instrument (instrument_name) VALUES ('Harmonica');
INSERT INTO instrument (instrument_name) VALUES ('Accordion');
INSERT INTO instrument (instrument_name) VALUES ('Turntable');
INSERT INTO instrument (instrument_name) VALUES ('Drum Machine');
INSERT INTO instrument (instrument_name) VALUES ('Sampler');
INSERT INTO instrument (instrument_name) VALUES ('MIDI Controller');
INSERT INTO instrument (instrument_name) VALUES ('Tabla');
INSERT INTO instrument (instrument_name) VALUES ('Sitar');