-- Clearing triggers

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT tgname AS trigger_name, tgrelid::regclass AS table_name
        FROM pg_trigger
        WHERE NOT tgisinternal
    LOOP
        EXECUTE 'DROP TRIGGER IF EXISTS ' || r.trigger_name || ' ON ' || r.table_name;
    END LOOP;
END;
$$;

-- Inserting into assets

CREATE OR REPLACE FUNCTION INSERT_INTO_ASSET()
RETURNS TRIGGER AS $$
DECLARE
    AID integer;

BEGIN
    INSERT INTO asset (asset_type) VALUES (TG_ARGV[0]::asset_type_enum) RETURNING asset_id INTO AID;
    NEW.asset_id = AID;
    RETURN NEW;

END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER USER_INSERT_TRIGGER
BEFORE INSERT
ON users
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('user');

CREATE TRIGGER SONG_INSERT_TRIGGER
BEFORE INSERT
ON song
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('song');

CREATE TRIGGER ALBUM_INSERT_TRIGGER
BEFORE INSERT
ON album
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('album');

CREATE TRIGGER PLAYLIST_INSERT_TRIGGER
BEFORE INSERT
ON playlist
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('playlist');

CREATE TRIGGER PRODUCT_INSERT_TRIGGER
BEFORE INSERT
ON product
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('product');

CREATE TRIGGER REPORT_INSERT_TRIGGER
BEFORE INSERT
ON report
FOR EACH ROW
EXECUTE FUNCTION INSERT_INTO_ASSET('report');