version: "3.9"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app.log:/backend/app.log

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - backend